[project]
name = "mooneazy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "requests",
    "betterplaysound",
    "pytest"
]

[tool.setuptools]
packages = [
    "alerts", 
    "backtesting", 
    "candles_api", 
    "range_strategy", 
    "ultimate_setups", 
    "breakout_strategy", 
    "pullback_strategy"
]

